### ISSUE TITLE
Google Earth build fails

### ISSUE THREAD

**Issue by samteezy** [getsolus/3rd-party#58]
I have an existing install of Google Earth which fails to update. I primarily use eopkg3p, but I get an error when using the Software Center too.

Other apps, like Google Chrome or Slack Desktop, update just fine either way.

Below is the output from eopkg3p. The error below is the same I get in the Software Center UI: _Command "ar xf google-earth-pro-stable_7.3.4.8248_amd64.deb" failed, return value was 9._
```
The following packages are going to be upgraded:
google-earth
Continue? [Y/n]: Y
Building source package: google-earth
DEBUG: InstallDB initialized in 0.00418591499329.
DEBUG: RepoDB initialized in 9.29832458496e-05.
google-earth-pro-stable_7.3.4_amd64.deb [cached]
Unpacking archive(s)...
 unpacked (/var/eopkg/google-earth-7.3.4.8248-17/work)
Setting up source...
ar: google-earth-pro-stable_7.3.4.8248_amd64.deb: No such file or directory
DEBUG: return value for "ar xf google-earth-pro-stable_7.3.4.8248_amd64.deb" is 9
Program terminated.
Command "ar xf google-earth-pro-stable_7.3.4.8248_amd64.deb" failed, return value was 9.
Please use 'eopkg help' for general help.
Traceback (most recent call last):
  File "/home/sam/.local/bin/eopkg3p", line 8, in <module>
    sys.exit(cli())
  File "/home/sam/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sam/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sam/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sam/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sam/.local/lib/python3.7/site-packages/eopkg3p/cli.py", line 157, in upgrade
    eopkg = core.build_pspec(pspec)
  File "/home/sam/.local/lib/python3.7/site-packages/eopkg3p/core.py", line 95, in build_pspec
    [PKEXEC, EOPKG, "bi", "--ignore-safety", pspecfile, "-O", dest]
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/pkexec', '/usr/bin/eopkg', 'bi', '--ignore-safety', PosixPath('/home/sam/.cache/eopkg3p/3rd-party/network/web/google-earth/pspec.xml'), '-O', PosixPath('/home/sam/.cache/eopkg3p/builds/google-earth')]' returned non-zero exit status 1.
```

**Comment by Staudey** [comment]
Thanks for the heads-up! Fix incoming.
