### ISSUE TITLE
Google Earth build fails

### ISSUE THREAD

**Issue by samteezy** [getsolus/3rd-party#68]
Hey @Staudey, I'm finding that the Google Earth package build is failing. Googled the issue and apparently I reported (and you fixed) an identical issue last year! Hopefully a similar fix again. #58 

```
The following packages are going to be upgraded:
google-earth
Continue? [Y/n]: Y
Building source package: google-earth
DEBUG: InstallDB initialized in 0.00217509269714.
DEBUG: RepoDB initialized in 3.91006469727e-05.
Fetching source from: https://dl.google.com/dl/linux/direct/google-earth-pro-stable_7.3.6_amd64.deb
google-earth-pro-stable_7.3.6_amd64.deb (57.7 MB)100%     10.07 MB/s [00:00:00] [complete]
Source archive is stored: /var/cache/eopkg/archives/google-earth-pro-stable_7.3.6_amd64.deb
Unpacking archive(s)...
 unpacked (/var/eopkg/google-earth-7.3.6.9285-20/work)
Setting up source...
ar: google-earth-pro-stable_7.3.6.9285_amd64.deb: No such file or directory
DEBUG: return value for "ar xf google-earth-pro-stable_7.3.6.9285_amd64.deb" is 9
Program terminated.
Command "ar xf google-earth-pro-stable_7.3.6.9285_amd64.deb" failed, return value was 9.
Please use 'eopkg help' for general help.
Traceback (most recent call last):
  File "/home/sam/.local/bin/eopkg3p", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sam/.local/lib/python3.10/site-packages/eopkg3p/cli.py", line 157, in upgrade
    eopkg = core.build_pspec(pspec)
  File "/home/sam/.local/lib/python3.10/site-packages/eopkg3p/core.py", line 94, in build_pspec
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/pkexec', '/usr/bin/eopkg', 'bi', '--ignore-safety', PosixPath('/home/sam/.cache/eopkg3p/3rd-party/network/web/google-earth/pspec.xml'), '-O', PosixPath('/home/sam/.cache/eopkg3p/builds/google-earth')]' returned non-zero exit status 1.
```

**Comment by Staudey** [comment]
Thanks for the heads-up! That's what I get for adjusting the version after the fact (and then not running the build again, apparently)

I'm on mobile right now but I think the change should work

**Comment by samteezy** [comment]
Worked!
